# Generated by Django 3.2.8 on 2021-10-20 08:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('url', models.URLField(max_length=100, verbose_name='Ссылка')),
                ('target', models.SmallIntegerField(choices=[(0, '_self'), (1, '_blank')], default=0)),
                ('position', models.SmallIntegerField(choices=[('Header', 'Header'), ('Footer', 'Footer')], default='Header', verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Контент')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент')),
                ('content_uk', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Контент')),
                ('url', models.URLField(max_length=100, verbose_name='Ссылка')),
                ('target', models.SmallIntegerField(choices=[(0, '_self'), (1, '_blank')], default=0)),
                ('position', models.SmallIntegerField(choices=[(0, 'Header'), (1, 'Footer')], default='Header', verbose_name='Позиция')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
