# Generated by Django 3.2.9 on 2021-11-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.RemoveField(
            model_name='textpage',
            name='url',
        ),
    ]
