# Generated by Django 3.2.8 on 2021-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211011_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон'),
        ),
    ]
