# Generated by Django 3.2.9 on 2021-11-02 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211027_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='subscribes_set', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
