# Generated by Django 3.2.7 on 2021-10-05 08:18

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название')),
                ('title_uk', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('content_uk', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_uk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('images', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('average_rating', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Категория')),
                ('name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Категория')),
                ('name_uk', models.CharField(max_length=200, null=True, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SemiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('comment', ckeditor.fields.RichTextField()),
                ('is_published', models.BooleanField(default=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', related_query_name='comments_set', to='blog.article')),
                ('author', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('user', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_set', to='blog.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('alt', models.CharField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='blog.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='blog.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='blog.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_author', to='blog.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория'),
        ),
    ]
