# Generated by Django 3.2.7 on 2021-09-28 08:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Категория')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Категория')),
                ('name_uk', models.CharField(max_length=200, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SemiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='название')),
                ('name_uk', models.CharField(max_length=100, null=True, unique=True, verbose_name='название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название')),
                ('title_uk', models.CharField(max_length=250, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('content_uk', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_uk', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'good'), ('4', 'very good'), ('5', 'excellent')], max_length=10, verbose_name='Рейтинг')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Автор')),
                ('author_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Автор')),
                ('author_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Автор')),
                ('author_uk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория')),
                ('category_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория')),
                ('category_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория')),
                ('category_uk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semi_category', to='blog.semicategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
