# Generated by Django 3.2.7 on 2021-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'good'), ('4', 'very good'), ('5', 'excellent')], max_length=10, null=True, verbose_name='Рейтинг'),
        ),
    ]
