# Generated by Django 3.2.8 on 2021-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_articlerating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
