# Generated by Django 3.2.8 on 2021-10-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211019_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая'),
        ),
    ]
