# Generated by Django 3.2.8 on 2021-10-25 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_is_recommended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_uk',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Комментарий'),
        ),
    ]
