# Generated by Django 3.2.8 on 2021-10-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211027_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uk',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Категория'),
        ),
    ]
