# Generated by Django 3.2.8 on 2021-10-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211028_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_uk',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
