# Generated by Django 3.2.8 on 2021-10-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211029_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_uk',
        ),
    ]
